language: php

cache:
  directories:
    - ~/.composer/cache

php:
  - 5.6

sudo: false

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: e21a828679a86ff0c9889b37a8779050005cd0ae499f787785280214c2fbf30b

after_script:
  - ./bin/test-reporter
