language: php

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

services:
    - redis-server

php:
  - 5.4

sudo: false

before_install:
  - phpenv config-add .travis.php.ini
  - if [ -f ~/composer/composer.phar ]; then mv ~/composer/composer.phar ./; else wget https://getcomposer.org/composer.phar; fi
  - mkdir -p ~/composer
  - cp composer.phar ~/composer/composer.phar

install:
  - php -d memory_limit=-1 ./composer.phar install --no-progress --prefer-dist

script: ./bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=e21a828679a86ff0c9889b37a8779050005cd0ae499f787785280214c2fbf30b ./bin/test-reporter
