language: php

cache:
  directories:
    - ~/.composer/cache

services:
    - redis-server

php:
  - 5.4

sudo: false

before_install:
  - phpenv config-add .travis.php.ini

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=e21a828679a86ff0c9889b37a8779050005cd0ae499f787785280214c2fbf30b ./bin/test-reporter
